name: Run Localhost Tests

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull and Run the vBase Commitment Service Docker container
        run: |
          docker pull ghcr.io/validitybase/commitment-service-localhost:latest
          docker run -d -p 8545:8545 --name commitment-service ghcr.io/validitybase/commitment-service-localhost:latest
          sleep 10 # Wait for the Ethereum test node to start

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --network localhost

      - name: Stop and remove the Docker container
        run: |
          docker stop commitment-service
          docker rm commitment-service
