name: Run Localhost Tests

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Install dependencies
        uses: validityBase/vbase-github-actions/.github/actions/setup-node-deps@v1
        with:
          node-version: "18"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull and Run the vBase Commitment Service Docker container
        run: |
          docker pull ghcr.io/validitybase/commitment-service-localhost:latest
          docker run -d -p 8545:8545 --name commitment-service ghcr.io/validitybase/commitment-service-localhost:latest
          sleep 10 # Wait for the Ethereum test node to start

      - name: Run tests
        run: npm run test:spec:localhost

      - name: Stop and remove the Docker container
        if: always()
        run: |
          docker stop commitment-service || true
          docker rm commitment-service || true
