name: Update the Main Docs Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update-main-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Install dependencies
        uses: validityBase/vbase-github-actions/.github/actions/setup-node-deps@v1
        with:
          node-version: "18"

      - name: Build Markdown docs
        run: npm run docs:build

      - name: Publish Documents
        uses: validityBase/vbase-github-actions/.github/actions/publish-docs@v1
        with:
          docs-repo-access-token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          source-docs-path: "_docs"
          target-repository-branch: main
